<template>
	<div class="cdx-playground">
		<div class="cdx-playground-column1">
			<AddNodeTool :index="0" />
			<!-- TODO set better key, maybe using autogenerated IDs -->
			<template
				v-for="( node, index ) in rootNode.children"
				:key="index"
			>
				<TemplateNodeEditor :index="index" />
				<AddNodeTool :index="index" />
			</template>
			<VariablesEditor />
		</div>
		<div class="cdx-playground-column2">
			<RenderDynamicApp />
			<SourceCode />
		</div>
	</div>
</template>

<script lang="ts">
import { defineComponent, computed, onMounted } from 'vue';
import AddNodeTool from './AddNodeTool.vue';
import RenderDynamicApp from './RenderDynamicApp.vue';
import SourceCode from './SourceCode.vue';
import TemplateNodeEditor from './TemplateNodeEditor.vue';
import VariablesEditor from './VariablesEditor.vue';

import '@wikimedia/codex/dist/codex.style.css';
import { useStore } from './store';

export default defineComponent( {
	components: {
		AddNodeTool,
		RenderDynamicApp,
		SourceCode,
		TemplateNodeEditor,
		VariablesEditor
	},
	setup() {
		const store = useStore();
		const rootNode = computed( () => store.template );

		onMounted( () => {
			store.updateStoreFromHash();
			store.$subscribe( () => store.updateHashFromStore() );
		} );

		return {
			rootNode
		};
	}
} );
</script>

<style lang="less">
.cdx-playground {
	display: flex;
	height: 100%;
	box-sizing: border-box;

	&-column1 {
		width: 35%;
		padding: 1em;
	}

	&-column2 {
		display: flex;
		flex-direction: column;
		width: 65%;
		padding: 1em;
	}

	.cdx-playground-render {
		flex-grow: 1;
	}
}
</style>
